name: Build Status

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            distribution: zulu
          - os: ubuntu-latest
            java: 17
            distribution: temurin
          - os: ubuntu-latest
            java: 21
            distribution: temurin
          - os: macos-latest
            java: 11
            distribution: temurin
          - os: windows-latest
            java: 8
            distribution: zulu
    runs-on: ${{ matrix.os }}
    env:
      JAVA_OPTS: -Dsbt.io.virtual=false -Dfile.encoding=UTF-8
      JVM_OPTS: -Dsbt.io.virtual=false -Dfile.encoding=UTF-8
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: "${{ matrix.distribution }}"
        java-version: "${{ matrix.java }}"
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      shell: bash
      run: sbt -v test
